// backend/src/services/pdf.service.js
'use strict';

/**
 * PDF Service
 * Handles: overlay QR stamp onto PDF, versioning, coordinate conversion
 * Uses: pdf-lib
 *
 * Coordinate system notes:
 * - Browser / frontend: origin TOP-LEFT, pixels
 * - PDF (pdf-lib): origin BOTTOM-LEFT, points (1pt = 1/72 inch)
 * - We store x_percent, y_percent (0-100%) relative to page size
 * - Conversion: xPt = (xPercent/100) * pageWidthPt
 *               yPt = pageHeightPt - (yPercent/100) * pageHeightPt - heightPt
 *               (flip Y because PDF origin is bottom-left)
 *
 * Signing level chain:
 *   Level 0 (Staff)   → reads: pathOriginal       → writes: pathSignedLevel0
 *   Level 1 (SPV)     → reads: pathSignedLevel0   → writes: pathSignedLevel1
 *   Level 2 (Final)   → reads: pathSignedLevel1   → writes: pathSignedFinal
 *
 * QR-per-approval (CHANGED):
 *   Each approval row owns its own QR (approval.qrPath), generated by
 *   qrService.generateApprovalQr() BEFORE calling overlayEsign. This QR both
 *   (a) gets stamped onto the PDF at that level, and (b) is the public
 *   verification target /e/approval/{approvalId}. The old single
 *   document.qrPathEsign is no longer read here.
 */

const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const path   = require('path');
const fs     = require('fs');
const { prisma } = require('../config/prisma');
const logger     = require('../config/logger');

/**
 * Footer stamp (ID Regulatory / Nama Label / Nama File):
 * Drawn ONCE, at Level 0 (Staff Regulatory's own upload/approval step), at a
 * position Staff Regulatory drags on-screen — same drag UX as the QR box.
 * Because each subsequent level's overlay reads and rebuilds on top of the
 * PREVIOUS level's already-stamped output file (see signing chain above),
 * the footer drawn at Level 0 is physically baked into every later file —
 * it is NEVER redrawn at level 1/2, which would create duplicate/overlapping
 * text. See overlayEsign() below.
 *
 * Placed on EVERY page of the PDF (not just the QR page), since the whole
 * point is "which record does this piece of paper belong to" — a reader
 * could be looking at any page.
 */
const FOOTER_FONT_SIZE  = 7;
const FOOTER_COLOR      = rgb(0.55, 0.55, 0.55); // gray
const FOOTER_MARGIN_PT  = 18; // legacy fallback margin, used only if no position/default is resolvable
const FOOTER_LINE_GAP   = 9;

function truncate(str, max) {
  if (!str) return '';
  return str.length > max ? str.slice(0, max - 1) + '…' : str;
}

/**
 * @param {Object} footerPos - { pageNumber, xPercent, yPercent, widthPt, heightPt }
 *                             (already resolved/validated by the caller)
 */
async function drawFooter(pdfDoc, document, footerPos) {
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const lines = [
    `ID Regulatory: ${document.regulatoryId}`,
    `Nama Label: ${truncate(document.labelName, 90)}`,
    `Nama File: ${truncate(document.fileNameOriginal, 90)}`,
  ];

  for (const page of pdfDoc.getPages()) {
    const { width, height } = page.getSize();
    const xPt = footerPos ? (footerPos.xPercent / 100) * width : FOOTER_MARGIN_PT;
    // Same convention as the QR box: xPercent/yPercent is the box's top-left
    // corner (percent-of-page, top-left origin); subtract heightPt to land on
    // the bottom of the box, which is where the 3-line block's baseline sits.
    const yPt = footerPos
      ? height - (footerPos.yPercent / 100) * height - footerPos.heightPt
      : FOOTER_MARGIN_PT;
    const maxWidth = footerPos ? footerPos.widthPt : width - FOOTER_MARGIN_PT * 2;

    lines.forEach((line, i) => {
      page.drawText(line, {
        x: xPt,
        y: yPt + (lines.length - 1 - i) * FOOTER_LINE_GAP,
        size: FOOTER_FONT_SIZE,
        font,
        color: FOOTER_COLOR,
        maxWidth,
      });
    });
  }
}

/**
 * Get system settings as parsed floats
 */
async function getSettings() {
  const rows = await prisma.systemSetting.findMany();
  const map  = Object.fromEntries(rows.map(r => [r.key, parseFloat(r.value)]));
  return {
    defaultWidthPt:  map.qr_default_width_pt  || 100,
    defaultHeightPt: map.qr_default_height_pt || 100,
    defaultPage:     map.qr_default_page       || 1,
    defaultXPercent: map.qr_default_x_percent  || 85,
    defaultYPercent: map.qr_default_y_percent  || 5,
    minWidthPt:      map.qr_min_width_pt       || 10,
    maxWidthPt:      map.qr_max_width_pt       || 200,
    // Footer stamp defaults — chosen to reproduce the old hardcoded bottom-left
    // ~18pt margin look on an A4-ish (~595pt wide) page for documents that are
    // never dragged (e.g. legacy behavior before this feature existed).
    footerDefaultXPercent: map.footer_default_x_percent  || 3,
    footerDefaultYPercent: map.footer_default_y_percent  || 97,
    footerDefaultWidthPt:  map.footer_default_width_pt   || 220,
    footerDefaultHeightPt: map.footer_default_height_pt  || 30,
    footerDefaultPage:     map.footer_default_page       || 1,
  };
}

/**
 * Validate and clamp position values
 */
function validatePosition(pos, settings) {
  const xPercent = Math.max(0, Math.min(100, pos.xPercent));
  const yPercent = Math.max(0, Math.min(100, pos.yPercent));
  const widthPt  = Math.max(settings.minWidthPt, Math.min(settings.maxWidthPt, pos.widthPt));
  const heightPt = Math.max(settings.minWidthPt, Math.min(settings.maxWidthPt, pos.heightPt));
  return { pageNumber: pos.pageNumber || 1, xPercent, yPercent, widthPt, heightPt };
}

/**
 * Validate and clamp footer position values
 */
function validateFooterPosition(pos) {
  const xPercent = Math.max(0, Math.min(100, pos.xPercent));
  const yPercent = Math.max(0, Math.min(100, pos.yPercent));
  const widthPt  = Math.max(50, Math.min(400, pos.widthPt));
  const heightPt = Math.max(15, Math.min(100, pos.heightPt));
  return { pageNumber: pos.pageNumber || 1, xPercent, yPercent, widthPt, heightPt };
}

/**
 * Resolve source PDF path based on signing level.
 *
 *   level 0 → source: pathOriginal       (staff signs original)
 *   level 1 → source: pathSignedLevel0   (SPV signs staff-signed copy)
 *   level 2 → source: pathSignedLevel1   (final approver signs SPV-signed copy)
 */
function resolveSourcePath(document, level) {
  if (level === 0) {
    if (!document.pathOriginal || !fs.existsSync(document.pathOriginal)) {
      throw new Error(`Original PDF not found for document ${document.id}`);
    }
    return document.pathOriginal;
  }

  if (level === 1) {
    if (!document.pathSignedLevel0 || !fs.existsSync(document.pathSignedLevel0)) {
      throw new Error(`Level 0 signed PDF not found for document ${document.id}. Staff must sign first.`);
    }
    return document.pathSignedLevel0;
  }

  if (level === 2) {
    if (!document.pathSignedLevel1 || !fs.existsSync(document.pathSignedLevel1)) {
      throw new Error(`Level 1 signed PDF not found for document ${document.id}. SPV must sign first.`);
    }
    return document.pathSignedLevel1;
  }

  throw new Error(`Unsupported approval level: ${level}`);
}

/**
 * Resolve output filename based on signing level.
 */
function resolveOutputFilename(level) {
  const map = { 0: 'signed_level0.pdf', 1: 'signed_level1.pdf', 2: 'signed_final.pdf' };
  if (!(level in map)) throw new Error(`Unsupported approval level: ${level}`);
  return map[level];
}

/**
 * Overlay this approval's own QR stamp on PDF at specified position.
 *
 * IMPORTANT (changed): the QR image embedded is `approval.qrPath`, NOT
 * `document.qrPathEsign`. Caller MUST generate and persist approval.qrPath
 * (via qrService.generateApprovalQr) before calling this function — see
 * usage in document.controller.js (level 0) and approval.controller.js
 * (level 1+).
 *
 * @param {Object}      document - Prisma document record
 * @param {Object}      approval - Prisma document_approval record; MUST include
 *                                 `.level` and `.qrPath` (already generated)
 * @param {Object|null} position - { pageNumber, xPercent, yPercent, widthPt, heightPt }
 *                                 or null to use system defaults
 * @param {boolean}     isFinalLevel - unused by the footer stamp (see below);
 *                                 kept for callers that still pass it.
 * @param {Object|null} footerPosition - { pageNumber, xPercent, yPercent, widthPt, heightPt }
 *                                 for the ID Regulatory/Nama Label/Nama File stamp,
 *                                 or null to use system defaults. Only honored when
 *                                 approval.level === 0 — Staff Regulatory is the only
 *                                 level that sets this; it is then physically baked
 *                                 into pathSignedLevel0 and carried forward unchanged
 *                                 through every later level's rebuild (see module
 *                                 header "Signing level chain").
 * @returns {string} absolute path to the newly written signed PDF
 */
async function overlayEsign(document, approval, position, isFinalLevel = false, footerPosition = null) {
  const settings = await getSettings();

  const pos = position
    ? validatePosition(position, settings)
    : {
        pageNumber: settings.defaultPage,
        xPercent:   settings.defaultXPercent,
        yPercent:   settings.defaultYPercent,
        widthPt:    settings.defaultWidthPt,
        heightPt:   settings.defaultHeightPt,
      };

  const level      = approval.level;
  const sourcePath = resolveSourcePath(document, level);

  const pdfBytes = fs.readFileSync(sourcePath);
  const pdfDoc   = await PDFDocument.load(pdfBytes);
  const pages    = pdfDoc.getPages();

  const pageIndex = Math.max(0, Math.min(pages.length - 1, pos.pageNumber - 1));
  const page      = pages[pageIndex];
  const { width: pageWidthPt, height: pageHeightPt } = page.getSize();

  const xPt = (pos.xPercent / 100) * pageWidthPt;
  const yPt = pageHeightPt - (pos.yPercent / 100) * pageHeightPt - pos.heightPt;

  // CHANGED: use this approval's own QR, not document.qrPathEsign
  const qrPath = approval.qrPath;
  if (!qrPath || !fs.existsSync(qrPath)) {
    throw new Error(
      `Approval QR not found for approval ${approval.id} (level ${level}). ` +
      `Call qrService.generateApprovalQr() and persist approval.qrPath before overlayEsign().`
    );
  }

  const qrImageBytes = fs.readFileSync(qrPath);
  const qrImage      = await pdfDoc.embedPng(qrImageBytes);

  page.drawImage(qrImage, {
    x:      xPt,
    y:      Math.max(0, yPt),
    width:  pos.widthPt,
    height: pos.heightPt,
  });

  if (level === 0) {
    const resolvedFooterPos = footerPosition
      ? validateFooterPosition(footerPosition)
      : {
          pageNumber: settings.footerDefaultPage,
          xPercent:   settings.footerDefaultXPercent,
          yPercent:   settings.footerDefaultYPercent,
          widthPt:    settings.footerDefaultWidthPt,
          heightPt:   settings.footerDefaultHeightPt,
        };
    await drawFooter(pdfDoc, document, resolvedFooterPos);
  }
  // Levels 1/2 draw nothing here — the footer is already physically baked
  // into the source PDF this level reads from (see resolveSourcePath), so
  // redrawing would create duplicate/overlapping text.

  const storageDir  = path.dirname(sourcePath);
  const outFilename = resolveOutputFilename(level);
  const outPath     = path.join(storageDir, outFilename);

  const signedBytes = await pdfDoc.save();
  fs.writeFileSync(outPath, signedBytes);

  logger.info(
    `PDF signed [level ${level}, approval ${approval.id}]: ${outPath} | ` +
    `page ${pos.pageNumber} | x=${xPt.toFixed(1)}pt y=${yPt.toFixed(1)}pt`
  );

  return outPath;
}

module.exports = { overlayEsign, getSettings };
