// backend/src/services/pdf.service.js
'use strict';

/**
 * PDF Service
 * Handles: overlay QR stamp onto PDF, versioning, coordinate conversion
 * Uses: pdf-lib
 *
 * Coordinate system notes:
 * - Browser / frontend: origin TOP-LEFT, pixels
 * - PDF (pdf-lib): origin BOTTOM-LEFT, points (1pt = 1/72 inch)
 * - We store x_percent, y_percent (0-100%) relative to page size
 * - Conversion: xPt = (xPercent/100) * pageWidthPt
 *               yPt = pageHeightPt - (yPercent/100) * pageHeightPt - heightPt
 *               (flip Y because PDF origin is bottom-left)
 *
 * Signing level chain:
 *   Level 0 (Staff)   → reads: pathOriginal       → writes: pathSignedLevel0
 *   Level 1 (SPV)     → reads: pathSignedLevel0   → writes: pathSignedLevel1
 *   Level 2 (Final)   → reads: pathSignedLevel1   → writes: pathSignedFinal
 *
 * QR-per-approval (CHANGED):
 *   Each approval row owns its own QR (approval.qrPath), generated by
 *   qrService.generateApprovalQr() BEFORE calling overlayEsign. This QR both
 *   (a) gets stamped onto the PDF at that level, and (b) is the public
 *   verification target /e/approval/{approvalId}. The old single
 *   document.qrPathEsign is no longer read here.
 */

const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const path   = require('path');
const fs     = require('fs');
const { prisma } = require('../config/prisma');
const logger     = require('../config/logger');

/**
 * Footer stamp (added for the "footer e-sign" feature):
 * Drawn ONLY on the final signed copy (pathSignedFinal) — i.e. when
 * overlayEsign() is called with isFinalLevel = true. It is NOT drawn on
 * intermediate copies (pathSignedLevel0, pathSignedLevel1), per business
 * decision confirmed with the requester: footer only appears once every
 * approval level is complete, as a tamper-evident marker binding the
 * physical file to its DB record (regulatoryId, labelName, fileName).
 *
 * Placed on EVERY page of the final PDF (not just the QR page), since the
 * whole point is "which record does this piece of paper belong to" —
 * a reader could be looking at any page.
 */
const FOOTER_FONT_SIZE  = 7;
const FOOTER_COLOR      = rgb(0.55, 0.55, 0.55); // gray
const FOOTER_MARGIN_PT  = 18;
const FOOTER_LINE_GAP   = 9;

function truncate(str, max) {
  if (!str) return '';
  return str.length > max ? str.slice(0, max - 1) + '…' : str;
}

async function drawFooter(pdfDoc, document) {
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const lines = [
    `ID Regulatory: ${document.regulatoryId}`,
    `Nama Label: ${truncate(document.labelName, 90)}`,
    `Nama File: ${truncate(document.fileNameOriginal, 90)}`,
  ];

  for (const page of pdfDoc.getPages()) {
    const { width } = page.getSize();
    lines.forEach((line, i) => {
      page.drawText(line, {
        x: FOOTER_MARGIN_PT,
        y: FOOTER_MARGIN_PT + (lines.length - 1 - i) * FOOTER_LINE_GAP,
        size: FOOTER_FONT_SIZE,
        font,
        color: FOOTER_COLOR,
        maxWidth: width - FOOTER_MARGIN_PT * 2,
      });
    });
  }
}

/**
 * Get system settings as parsed floats
 */
async function getSettings() {
  const rows = await prisma.systemSetting.findMany();
  const map  = Object.fromEntries(rows.map(r => [r.key, parseFloat(r.value)]));
  return {
    defaultWidthPt:  map.qr_default_width_pt  || 100,
    defaultHeightPt: map.qr_default_height_pt || 100,
    defaultPage:     map.qr_default_page       || 1,
    defaultXPercent: map.qr_default_x_percent  || 85,
    defaultYPercent: map.qr_default_y_percent  || 5,
    minWidthPt:      map.qr_min_width_pt       || 60,
    maxWidthPt:      map.qr_max_width_pt       || 200,
  };
}

/**
 * Validate and clamp position values
 */
function validatePosition(pos, settings) {
  const xPercent = Math.max(0, Math.min(100, pos.xPercent));
  const yPercent = Math.max(0, Math.min(100, pos.yPercent));
  const widthPt  = Math.max(settings.minWidthPt, Math.min(settings.maxWidthPt, pos.widthPt));
  const heightPt = Math.max(settings.minWidthPt, Math.min(settings.maxWidthPt, pos.heightPt));
  return { pageNumber: pos.pageNumber || 1, xPercent, yPercent, widthPt, heightPt };
}

/**
 * Resolve source PDF path based on signing level.
 *
 *   level 0 → source: pathOriginal       (staff signs original)
 *   level 1 → source: pathSignedLevel0   (SPV signs staff-signed copy)
 *   level 2 → source: pathSignedLevel1   (final approver signs SPV-signed copy)
 */
function resolveSourcePath(document, level) {
  if (level === 0) {
    if (!document.pathOriginal || !fs.existsSync(document.pathOriginal)) {
      throw new Error(`Original PDF not found for document ${document.id}`);
    }
    return document.pathOriginal;
  }

  if (level === 1) {
    if (!document.pathSignedLevel0 || !fs.existsSync(document.pathSignedLevel0)) {
      throw new Error(`Level 0 signed PDF not found for document ${document.id}. Staff must sign first.`);
    }
    return document.pathSignedLevel0;
  }

  if (level === 2) {
    if (!document.pathSignedLevel1 || !fs.existsSync(document.pathSignedLevel1)) {
      throw new Error(`Level 1 signed PDF not found for document ${document.id}. SPV must sign first.`);
    }
    return document.pathSignedLevel1;
  }

  throw new Error(`Unsupported approval level: ${level}`);
}

/**
 * Resolve output filename based on signing level.
 */
function resolveOutputFilename(level) {
  const map = { 0: 'signed_level0.pdf', 1: 'signed_level1.pdf', 2: 'signed_final.pdf' };
  if (!(level in map)) throw new Error(`Unsupported approval level: ${level}`);
  return map[level];
}

/**
 * Overlay this approval's own QR stamp on PDF at specified position.
 *
 * IMPORTANT (changed): the QR image embedded is `approval.qrPath`, NOT
 * `document.qrPathEsign`. Caller MUST generate and persist approval.qrPath
 * (via qrService.generateApprovalQr) before calling this function — see
 * usage in document.controller.js (level 0) and approval.controller.js
 * (level 1+).
 *
 * @param {Object}      document - Prisma document record
 * @param {Object}      approval - Prisma document_approval record; MUST include
 *                                 `.level` and `.qrPath` (already generated)
 * @param {Object|null} position - { pageNumber, xPercent, yPercent, widthPt, heightPt }
 *                                 or null to use system defaults
 * @param {boolean}     isFinalLevel - if true, also stamps the gray footer
 *                                 (ID Regulatory / Nama Label / Nama File)
 *                                 on every page. Caller is responsible for
 *                                 determining finality (see
 *                                 approval.controller.js resolveIsFinalLevel).
 * @returns {string} absolute path to the newly written signed PDF
 */
async function overlayEsign(document, approval, position, isFinalLevel = false) {
  const settings = await getSettings();

  const pos = position
    ? validatePosition(position, settings)
    : {
        pageNumber: settings.defaultPage,
        xPercent:   settings.defaultXPercent,
        yPercent:   settings.defaultYPercent,
        widthPt:    settings.defaultWidthPt,
        heightPt:   settings.defaultHeightPt,
      };

  const level      = approval.level;
  const sourcePath = resolveSourcePath(document, level);

  const pdfBytes = fs.readFileSync(sourcePath);
  const pdfDoc   = await PDFDocument.load(pdfBytes);
  const pages    = pdfDoc.getPages();

  const pageIndex = Math.max(0, Math.min(pages.length - 1, pos.pageNumber - 1));
  const page      = pages[pageIndex];
  const { width: pageWidthPt, height: pageHeightPt } = page.getSize();

  const xPt = (pos.xPercent / 100) * pageWidthPt;
  const yPt = pageHeightPt - (pos.yPercent / 100) * pageHeightPt - pos.heightPt;

  // CHANGED: use this approval's own QR, not document.qrPathEsign
  const qrPath = approval.qrPath;
  if (!qrPath || !fs.existsSync(qrPath)) {
    throw new Error(
      `Approval QR not found for approval ${approval.id} (level ${level}). ` +
      `Call qrService.generateApprovalQr() and persist approval.qrPath before overlayEsign().`
    );
  }

  const qrImageBytes = fs.readFileSync(qrPath);
  const qrImage      = await pdfDoc.embedPng(qrImageBytes);

  page.drawImage(qrImage, {
    x:      xPt,
    y:      Math.max(0, yPt),
    width:  pos.widthPt,
    height: pos.heightPt,
  });

  if (isFinalLevel) {
    await drawFooter(pdfDoc, document);
  }

  const storageDir  = path.dirname(sourcePath);
  const outFilename = resolveOutputFilename(level);
  const outPath     = path.join(storageDir, outFilename);

  const signedBytes = await pdfDoc.save();
  fs.writeFileSync(outPath, signedBytes);

  logger.info(
    `PDF signed [level ${level}, approval ${approval.id}]: ${outPath} | ` +
    `page ${pos.pageNumber} | x=${xPt.toFixed(1)}pt y=${yPt.toFixed(1)}pt`
  );

  return outPath;
}

module.exports = { overlayEsign, getSettings };