#!/bin/bash
# deploy/nginx.sh — Configure Nginx for DAL System
# Run: sudo bash deploy/nginx.sh

set -euo pipefail

DOMAIN="${1:-dal.yourdomain.com}"
APP_DIR="/var/www/dal-system"

echo "[Nginx] Configuring for domain: $DOMAIN"

# ─── Write Nginx config ───────────────────────────────────────────────────────
cat > /etc/nginx/sites-available/dal-system <<NGINX
# DAL System — Nginx Configuration
# Generated by deploy/nginx.sh

# Limit request body size
client_max_body_size 12M;

# Rate limiting zones
limit_req_zone \$binary_remote_addr zone=dal_login:10m  rate=5r/m;
limit_req_zone \$binary_remote_addr zone=dal_upload:10m rate=10r/m;
limit_req_zone \$binary_remote_addr zone=dal_api:10m    rate=60r/m;
limit_req_zone \$binary_remote_addr zone=dal_public:10m rate=30r/m;

server {
    listen 80;
    server_name ${DOMAIN};

    # Security headers
    add_header X-Frame-Options           "DENY"                  always;
    add_header X-Content-Type-Options    "nosniff"               always;
    add_header X-XSS-Protection          "1; mode=block"         always;
    add_header Referrer-Policy           "strict-origin"         always;
    add_header Permissions-Policy        "geolocation=(), camera=(), microphone=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Hide server version
    server_tokens off;

    # ─── Frontend (React SPA) ─────────────────────────────────────
    root ${APP_DIR}/frontend;
    index index.html;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_types text/plain text/css application/json application/javascript text/javascript image/svg+xml;
    gzip_min_length 1024;

    # Static assets with long cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|map)\$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # ─── API proxy → Backend Express ──────────────────────────────
    location /api/auth/login {
        limit_req zone=dal_login burst=10 nodelay;
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_set_header   Connection        "";
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
    }

    # Upload (POST only) — strict rate limit (LOW-09 fix)
    location = /api/documents {
        limit_req zone=dal_api burst=30 nodelay;
        client_max_body_size 12M;
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        proxy_buffering    off;
    }

    # File upload endpoint — upload-specific rate limit
    location = /api/documents/upload {
        limit_req zone=dal_upload burst=5 nodelay;
        client_max_body_size 12M;
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        proxy_buffering    off;
    }

    # Document file serving — longer timeout for PDFs
    location ~ ^/api/documents/[^/]+/(original|signed|report|qr) {
        limit_req zone=dal_api burst=20 nodelay;
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        proxy_buffering    off;
    }

    location /api/e/ {
        limit_req zone=dal_public burst=20 nodelay;
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 15s;
    }

    location /api/ {
        limit_req zone=dal_api burst=30 nodelay;
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_set_header   Connection        "";
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    location /health {
        proxy_pass         http://127.0.0.1:3001;
        access_log         off;
        proxy_read_timeout 5s;
    }

    # ─── SPA Fallback ─────────────────────────────────────────────
    location / {
        try_files \$uri \$uri/ /index.html;
        # No caching for index.html
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # ─── Block sensitive paths ────────────────────────────────────
    location ~ /\. { deny all; return 404; }
    location ~ \.env\$ { deny all; return 404; }
    location ~ /node_modules/ { deny all; return 404; }
    location ~ /prisma/ { deny all; return 404; }

    # ─── Logging ──────────────────────────────────────────────────
    access_log /var/log/nginx/dal-access.log combined;
    error_log  /var/log/nginx/dal-error.log  warn;
}
NGINX

# Disable default site, enable dal-system
ln -sf /etc/nginx/sites-available/dal-system /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Test and reload
nginx -t
systemctl reload nginx

echo "[Nginx] ✅ Configuration applied for ${DOMAIN}"
echo "[Nginx]    Access log: /var/log/nginx/dal-access.log"
echo "[Nginx]    Error log:  /var/log/nginx/dal-error.log"
echo ""
echo "For HTTPS, run:"
echo "  apt install certbot python3-certbot-nginx -y"
echo "  certbot --nginx -d ${DOMAIN}"
